### PR TITLE
Get rid of simple form warning

### PR DESCRIPTION
**Pull request by dlupu**
We're using Rails Db in one of our projects and we see this warning in our logs

> Simple Form is not configured in the application and will use the default values. Use `rails generate simple_form:install` to generate the Simple Form configuration.

Since we do not use simple form, we have tracked down the source of the warning to this gem.  Here is a pull request to get rid of this warning by including the files generated by `rails generate simple_form:install`

### CODE REVIEW

**Comment by franzejr** [comment]
:+1:

**Comment by igorkasyanchuk** [comment]
Please fix Travis CI issue https://travis-ci.org/igorkasyanchuk/rails_db/jobs/105137635
Only if tests are passed I can merge it

**Comment by dlupu** [comment]
Yep. Will do that asap. Today is quite a busy day .

**Comment by igorkasyanchuk** [comment]
@dlupu any luck with PR? :)

**Comment by dlupu** [comment]
Hello Igor, 

Sorry not yet, it's a very busy period, until the end of the month.

**Comment by igorkasyanchuk** [comment]
@dlupu maybe if you want you can fix your PR and I'll merge it

**Comment by igorkasyanchuk** [comment]
@dlupu do you want to merge it? or I could fix this issue my myself?

**Pull request merged**
